name: Integration Tests
on:
  workflow_dispatch:
  # pull_request:
  push:
  #   branches:
  #     - 'main'
permissions:
  contents: read
jobs:
  test:
    name: Integration Tests (Github Runners)
    environment: INT
    runs-on: [ubuntu-latest]
    env:
      1envtest: "Test ENV Settings on Job"
    steps:
      - name: Test Install - terraform
        uses: otc-code/action-tfe@first-release
        with:
          TF_DIR: '${{ github.workspace }}/test'
          TF_ACTION: 'install'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          TFE: 'terraform'
          TERRAFORM_VERSION: 'v1.5.0'
          FORCE_INSTALL: 'true'
