name: Integration Tests
on:
  workflow_dispatch:
  # pull_request:
  push:
  #   branches:
  #     - 'main'
permissions:
  contents: read
jobs:
  test:
    name: Integration Tests (Github Runners)
    environment: INT
    runs-on: [ubuntu-latest]
    steps:
      - name: Test Install
        uses: otc-code/action-tfe@first-release
        with:
          TF_ACTION: 'install'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_INSTALL: 'true'
          DEBUG: 'DEBUG'
